name: Test PR
'on': pull_request

jobs:
  install-and-test:
    name: 🛠️ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v7

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: 🗜️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 🛠️ Sync versions
        run: bun run script:sync-projects

      - name: 🧹 Lint
        run: bun run lint

      - name: ♻️ Check circular dependencies
        run: bun run check-circular-dependencies

      - name: 🧪 Run tests (ngx-update-app)
        run: bun run test ngx-update-app --coverage

      - name: 🧪 Run tests (demo)
        run: bun run test demo --coverage

      - name: 🧪 Report code coverage
        uses: ./.github/actions/report-pr
        with:
          coverage-file: coverage/**/cobertura-coverage.xml

      - name: ⬆️ Upload coverage reports
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          dry_run: true

      - name: 📦 Build demo app
        run: bun run build:demo --base-href https://celtian.github.io/ngx-update-app/

      - name: 📦 Build ngx-update-app
        run: bun run build
